# Generated by Django 5.2.10 on 2026-01-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_auto_20260120_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.URLField(blank=True, verbose_name='Изображение'),
        ),
    ]
