# Generated by Django 5.2.10 on 2026-01-20 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20260120_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='categories/', blank=True, verbose_name='Изображение'),
        ),
    ]
