# Generated by Codex on 2026-01-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_auto_20260120_1025"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image_url",
        ),
        migrations.AddField(
            model_name="product",
            name="code",
            field=models.CharField(blank=True, max_length=50, verbose_name="Код"),
        ),
        migrations.AddField(
            model_name="product",
            name="discount_percent",
            field=models.PositiveSmallIntegerField(default=0, verbose_name="Скидка, %"),
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, upload_to="products/", verbose_name="Изображение"),
        ),
        migrations.AddField(
            model_name="product",
            name="min_bonus_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Минимальная цена с бонусами"),
        ),
        migrations.AddField(
            model_name="product",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, verbose_name="Рейтинг"),
        ),
        migrations.AddField(
            model_name="product",
            name="rating_count",
            field=models.PositiveIntegerField(default=0, verbose_name="Количество оценок"),
        ),
        migrations.AddField(
            model_name="product",
            name="retail_price",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name="Розничная цена"),
        ),
        migrations.AddField(
            model_name="product",
            name="show_personal_price_difference",
            field=models.BooleanField(default=True, verbose_name="Показывать разницу персональной цены"),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("image", models.ImageField(upload_to="products/", verbose_name="Изображение")),
                ("alt_text", models.CharField(blank=True, max_length=200, verbose_name="Alt текст")),
                ("is_main", models.BooleanField(default=False, verbose_name="Основное")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="images", to="store.product", verbose_name="Товар")),
            ],
            options={
                "verbose_name": "Изображение товара",
                "verbose_name_plural": "Изображения товаров",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, verbose_name="Название")),
                ("value", models.CharField(max_length=200, verbose_name="Значение")),
                ("order", models.PositiveIntegerField(default=0, verbose_name="Порядок")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="attributes", to="store.product", verbose_name="Товар")),
            ],
            options={
                "verbose_name": "Характеристика товара",
                "verbose_name_plural": "Характеристики товаров",
                "ordering": ["order", "id"],
            },
        ),
    ]
