# Generated by Codex on 2026-01-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_product_brand"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="is_popular",
            field=models.BooleanField(default=False, verbose_name="Популярная на главной"),
        ),
        migrations.AddField(
            model_name="product",
            name="is_new",
            field=models.BooleanField(default=False, verbose_name="Новинка"),
        ),
    ]
