# Generated by Codex on 2026-01-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0014_category_is_popular_product_is_new"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="article",
            field=models.CharField(blank=True, max_length=50, verbose_name="Артикул"),
        ),
    ]
