# Generated by Codex on 2026-01-20

from django.db import migrations, models
import django.db.models.deletion
from django.utils.text import slugify


def forwards(apps, schema_editor):
    Attribute = apps.get_model("store", "Attribute")
    ProductAttribute = apps.get_model("store", "ProductAttribute")

    for product_attribute in ProductAttribute.objects.all():
        name = (product_attribute.name or "").strip()
        if not name:
            continue
        base_slug = slugify(name)[:140] or f"attr-{product_attribute.id}"
        slug = base_slug
        counter = 1
        while Attribute.objects.filter(slug=slug).exclude(name=name).exists():
            suffix = f"-{counter}"
            slug = f"{base_slug[: 140 - len(suffix)]}{suffix}"
            counter += 1
        attribute, created = Attribute.objects.get_or_create(
            name=name,
            defaults={"slug": slug, "data_type": "text"},
        )
        if not created and not attribute.slug:
            attribute.slug = slug
            attribute.save(update_fields=["slug"])
        product_attribute.attribute = attribute
        product_attribute.value_text = product_attribute.value
        product_attribute.save(update_fields=["attribute", "value_text"])


def backwards(apps, schema_editor):
    ProductAttribute = apps.get_model("store", "ProductAttribute")
    for product_attribute in ProductAttribute.objects.select_related("attribute").all():
        product_attribute.name = product_attribute.attribute.name if product_attribute.attribute else ""
        product_attribute.value = product_attribute.value_text or ""
        product_attribute.save(update_fields=["name", "value"])


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0015_product_article"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attribute",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=120, unique=True, verbose_name="Название")),
                ("slug", models.SlugField(max_length=140, unique=True, verbose_name="Слаг")),
                (
                    "data_type",
                    models.CharField(
                        choices=[("text", "Текст"), ("number", "Число"), ("boolean", "Да/Нет")],
                        default="text",
                        max_length=20,
                        verbose_name="Тип данных",
                    ),
                ),
                ("unit", models.CharField(blank=True, max_length=40, verbose_name="Единица измерения")),
                ("is_filterable", models.BooleanField(default=True, verbose_name="Фильтруется")),
            ],
            options={
                "verbose_name": "Атрибут",
                "verbose_name_plural": "Атрибуты",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="productattribute",
            name="attribute",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_attributes",
                to="store.attribute",
                verbose_name="Атрибут",
            ),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="value_text",
            field=models.CharField(blank=True, max_length=200, verbose_name="Текстовое значение"),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="value_number",
            field=models.DecimalField(
                blank=True,
                null=True,
                max_digits=12,
                decimal_places=3,
                verbose_name="Числовое значение",
            ),
        ),
        migrations.AddField(
            model_name="productattribute",
            name="value_bool",
            field=models.BooleanField(blank=True, null=True, verbose_name="Булево значение"),
        ),
        migrations.RunPython(forwards, backwards),
        migrations.RemoveField(
            model_name="productattribute",
            name="name",
        ),
        migrations.RemoveField(
            model_name="productattribute",
            name="value",
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="attribute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="product_attributes",
                to="store.attribute",
                verbose_name="Атрибут",
            ),
        ),
    ]
